name = "call-a-human"
main = "worker/src/index.ts"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "call-a-human-media"

[vars]
# TELEGRAM_TOKEN should be set via `wrangler secret put TELEGRAM_TOKEN`
# TELEGRAM_CHAT_ID can be set here or via `wrangler secret put`
TELEGRAM_CHAT_ID = "7514805353"
